### ISSUE TITLE
Toggle isn't really a toggle

### ISSUE THREAD

**Issue by rnhmjoj** [busyloop/maclight#1]
The `keyboard toggle` command doesn't toggle the state of the led.
You have to specify if you want to turn it off or on: it's a set, not a toggle.
Can you add an option to toggle the state?

I had to write this terrible script to do it:

``` bash
s=($(maclight keyboard toggle -v))
[ "${s[1]}" = 0 ] && maclight keyboard toggle -n 1 || maclight keyboard toggle -n 0
```

**Comment by m-o-e** [comment]
Sorry, don't have time for an update right now (a pull request would be considered).

For brevity you could use this one-liner:
`ruby -r maclight -e 'MacLight.capslock(!MacLight.capslock)'`

**Comment by rnhmjoj** [comment]
It's not important, don't worry.
I'll give a look at the code but I have never used ruby before.
Thank you.

**Comment by rnhmjoj** [comment]
I added the new option: it works fine. https://github.com/busyloop/maclight/pull/2

**Comment by m-o-e** [comment]
Thanks mate!

I've made a new release containing your change, you can update with `gem install maclight`.

**Comment by rnhmjoj** [comment]
Good. I close the issue then.
