### ISSUE TITLE
Maclight in OSX 10.10.5

### ISSUE THREAD

**Issue by ruslaniv** [busyloop/maclight#3]
This does not seem to work any more in OSX 10.10.5. Tested in 2 use cases:
1. Nothing remapped, Apple default settings for the keyboard.
2. Caps Lock disabled in system settings, remapped to F19 with Seil and F19 set to Hyper Key (CTRL + ALT + CMD) in Karabiner. 
$ maclight keyboard toggle --capslock
$ maclight keyboard toggle -v
1 0
But the Caps Lock light is off.

**Comment by m-o-e** [comment]
Maclight still works on latest OSX, but only for external keyboards,
not for laptops. It has always been that way, I should clarify that in the README.

As far as I know OSX unfortunately doesn't expose an API to toggle the
LEDs on laptop keyboards. If you find a way around that then
a pointer (or pull request) would be welcome!

**Comment by xiaket** [comment]
@m-o-e please add the above clarification in the README. I spent half an hour to find out this sad truth.

**Comment by m-o-e** [comment]
Compatibility notice added to README in 42105c1082ed71950939cf965c8a956459950805

Sorry for the inconvenience!
