### ISSUE TITLE
Works opposite to the way it is supposed to

### ISSUE THREAD

**Issue by ruslaniv** [busyloop/maclight#4]
Now i'm really puzzled. Maclight works now but works exactly the opposite way it is supposed to work. It toggles the lights on built in keyboard and does nothing on the external keyboard.
http://www.youtube.com/watch?v=V2SCIc34Bdc

**Comment by m-o-e** [comment]
Now this is really odd! 

I have never seen it work on a macbook keyboard.
Does that only happen _while_ an external keyboard is connected?

Also what laptop model and OSX version is this?

**Comment by ruslaniv** [comment]
It is MacBook Pro Retina, 13 inch, Late 2013. OSX 10.11.1 El Capitan.
No, it works both with external keyboard connected and external keyboard disconnected.
And it works in both use cases for internal keyboard only (with CAPS remapped to hyper key and CAPS in original state)

**Comment by m-o-e** [comment]
Hm, funny.

I'm afraid I have no idea why it works that way for you.

Thanks for the report, I'll just leave this open for now.
Perhaps one day someone can resolve this mystery for us.

**Comment by ruslaniv** [comment]
BTW,
this tool works on both internal and external keyboards simultaneously:
https://developer.apple.com/library/mac/samplecode/HID_LED_test_tool/Introduction/Intro.html
I added some more info in here:
http://superuser.com/questions/285103/is-it-possible-to-control-the-caps-lock-led-on-os-x 
how i achieved turning the caps light on and off on both keyboards. 
I wonder if you could maybe reuse some of that code.

**Comment by m-o-e** [comment]
> this tool works on both internal and external keyboards simultaneously:

I just tried it out, doesn't work on my Mba/ElCapitan either.

I really wonder what's different on your machine that causes this HID
code to work. Perhaps there's subtle differences between hardware revisions...
