### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by QuadDepo** [busyloop/maclight#5]
I was wondering if this project was still alive or not

**Comment by m-o-e** [comment]
Yep it is, why?

**Comment by QuadDepo** [comment]
Will it update to (High)Sierra?

**Comment by m-o-e** [comment]
I don't have High Sierra yet, does it not work there?

**Comment by QuadDepo** [comment]
i tried it on my 2015 macbook pro with sierra. but didnt work.

**Comment by m-o-e** [comment]
That is odd. `maclight keyboard test` works on my 2013 MBA and 2016 MBP, both on Sierra.
I'm afraid it might be a hardware compatibility issue.

**Comment by QuadDepo** [comment]
how could i check?

would it be possible to add ifttt to it? or anything else to create a sort of daskeyboard 5 effect?

**Comment by m-o-e** [comment]
I don't know how to check. If your hardware revision doesn't support the HID API
for keyboard LED control then I'm afraid you're out of luck on that device.

You can add everything you want, you have the source code right in front of you.

**Comment by QuadDepo** [comment]
Wait will this work on macbook keyboard, just tested it on my external one and it did work.

**Comment by m-o-e** [comment]
Yes, it should work on both internal and external. However, the API is not well
documented and it is possible that support varies by hardware revision.

**Comment by QuadDepo** [comment]
ah oke thanks, sorry for all the questions haha. one more togo

will it work on keys other than caps and numlock?

**Comment by m-o-e** [comment]
No problem, and no, only caps lock and numlock are supported
(and they can't be toggled individually in this version).
